manifest:
  remotes:
    - name: nicho
      url-base: https://github.com/nicho1asdev
  projects:
    - name: zmk
      remote: nicho
      revision: custom-effects
      import: app/west.yml
  self:
    path: config
